odometry:
  start_from_initial_coordinates: true
  noise:
    vel_bias_abs: true
    # x_bias_vel_coef: 0.01  # percentage from velocity, added to bias
    # y_bias_vel_coef: 0.01  # percentage from velocity, added to bias
    # yaw_bias_vel_coef: 0.05  # percentage from velocity, added to bias

    # x_std_dev_vel_coef: 0.1  # percentage from velocity, added to standard deviation
    # y_std_dev_vel_coef: 0.1  # percentage from velocity, added to standard deviation
    # yaw_std_dev_vel_coef: 0.1  # percentage from velocity, added to standard deviation

    # x_vel_static_bias: 0.0  # static value added to bias
    # y_vel_static_bias: 0.0  # static value added to bias
    # yaw_vel_static_bias: 0.0  # static value added to bias

    # x_vel_static_std_dev: 0.0  # static value added to standard deviation
    # y_vel_static_std_dev: 0.0  # static value added to standard deviation
    # yaw_vel_static_std_dev: 0.0  # static value added to standard deviation

    # Medium noise, still works I guess
    x_bias_vel_coef: 0.01  # percentage from velocity, added to bias
    y_bias_vel_coef: 0.01  # percentage from velocity, added to bias
    yaw_bias_vel_coef: 0.02  # percentage from velocity, added to bias

    x_std_dev_vel_coef: 0.1  # percentage from velocity, added to standard deviation
    y_std_dev_vel_coef: 0.1  # percentage from velocity, added to standard deviation
    yaw_std_dev_vel_coef: 0.1  # percentage from velocity, added to standard deviation

    x_vel_static_bias: 0.0001  # static value added to bias
    y_vel_static_bias: 0.0001  # static value added to bias
    yaw_vel_static_bias: 0.0005  # static value added to bias

    x_vel_static_std_dev: 0.001  # static value added to standard deviation
    y_vel_static_std_dev: 0.001  # static value added to standard deviation
    yaw_vel_static_std_dev: 0.0001  # static value added to standard deviation
    
    #High noise
    # x_bias_vel_coef: 0.01  # percentage from velocity, added to bias
    # y_bias_vel_coef: 0.01  # percentage from velocity, added to bias
    # yaw_bias_vel_coef: 0.05  # percentage from velocity, added to bias

    # x_std_dev_vel_coef: 0.1  # percentage from velocity, added to standard deviation
    # y_std_dev_vel_coef: 0.1  # percentage from velocity, added to standard deviation
    # yaw_std_dev_vel_coef: 0.1  # percentage from velocity, added to standard deviation

    # x_vel_static_bias: 0.0001  # static value added to bias
    # y_vel_static_bias: 0.0001  # static value added to bias
    # yaw_vel_static_bias: 0.0005  # static value added to bias

    # x_vel_static_std_dev: 0.001  # static value added to standard deviation
    # y_vel_static_std_dev: 0.001  # static value added to standard deviation
    # yaw_vel_static_std_dev: 0.0001  # static value added to standard deviation